<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <base href="<?php echo $this->basePath('/') ?>" />
        <title>ZF Markdown Wiki</title>
        <link rel="stylesheet/less" type="text/css" href="less/bootstrap.less">
        <script src="js/less-1.1.5.min.js" type="text/javascript"></script>
    </head>
    <body>

        <div class="container">

            <div class="content">
                <div class="page-header">
                    <h1>ZF Markdown Wiki <small>ZF2 + Twitter Bootstrap + Markdown</small></h1>
                </div>
                <div class="row">
                    <div class="span10">
                        <h2>Main content</h2>
                        <?php echo $this->raw('content'); ?>
                    </div>
                    <div class="span4">
                        <h3>Secondary content</h3>
                    </div>
                </div>
            </div>

            <footer>
                <p>&copy; Copyleft <?php echo date('Y') ?></p>
            </footer>

        </div>
    
    </body>
</html>