hello, world!
<?php



// Ups... following code may give "POSIX collating elements are not supported"
// warning, in case you have libpcre version 8.13 installed
// (see http://bugs.exim.org/show_bug.cgi?id=1136).
// Installing latest version (8.20) seems to fix this problem.
// In my case (openSUSE 12.1) I had to install v8.20 from Factory repositories.

echo $this->markdown('

header 1
========

* bullet 1
* bullet 2
* bullet 3

');

